version: '3.8'

services:
  mysql:
    image: mysql
    container_name: roles-management-mysql
    environment:
      MYSQL_DATABASE: roles_management_db
      MYSQL_USER: roles_management_db
      MYSQL_PASSWORD: roles_management_db
      MYSQL_ROOT_PASSWORD: roles_management_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - roles-management-network

volumes:
  mysql_data:

networks:
  roles-management-network:
    driver: bridge